const quotes = [
  "Hidup adalah tentang menciptakan diri sendiri.",
  "Setiap langkah yang kita ambil adalah langkah menuju sesuatu yang belum kita ketahui.",
  "Ketika satu pintu tertutup, pintu lain terbuka.",
  "Kesuksesan tidak selalu tentang memenangkan, tapi tentang tidak pernah menyerah.",
  "Jangan takut gagal, tapi takutlah tidak pernah mencoba.",
  "Keberhasilan dimulai dengan keputusan untuk mencoba.",
  "Setiap hari adalah kesempatan baru untuk menjadi versi terbaik dari dirimu sendiri.",
  "Rahasia menuju keberhasilan adalah fokus pada tujuan, bukan pada hasil.",
  "Hidup adalah perjalanan, bukan tujuan akhir.",
  "Yang sulit bukanlah langkah pertama, tetapi keputusan untuk mulai.",
  "Berkembang memerlukan keberanian untuk keluar dari zona nyaman.",
  "Hidup penuh warna, jangan biarkan dirimu terjebak dalam hitam putih.",
  "Semua impian dimulai dengan satu langkah kecil.",
  "Keberanian tidak selalu berteriak; kadang-kadang keberanian itu hanya sebatas suara lembut di akhir hari yang berkata, 'Aku akan mencoba lagi besok.'",
  "Tujuan tanpa tindakan hanyalah mimpi.",
  "Jangan biarkan hari ini menghentikan impian besokmu.",
  "Penting untuk berhenti sejenak dan bersyukur atas apa yang telah kamu capai.",
  "Keberhasilan adalah hasil dari kegigihan dan ketekunan.",
  "Jangan ragu untuk bermimpi besar, karena mimpi itulah yang memandu kita ke arah keberhasilan.",
  "Semua orang memiliki talenta unik; tugas kita adalah menemukan dan mengembangkan potensi terbaik dalam diri kita.",
  "Keberanian sejati adalah melihat ketidakpastian sebagai peluang, bukan sebagai ancaman.",
  "Jika kamu merasa lelah, beristirahatlah, bukan menyerah.",
  "Satu-satunya cara untuk melakukan pekerjaan besar adalah mencintai apa yang kamu lakukan.",
  "Tidak perlu menjadi sempurna, hanya perlu menjadi lebih baik dari kemarin.",
  "Ketahuilah bahwa setiap ujian yang datang adalah pembelajaran dan pembersihan bagi jiwa kita.",
  "Doa adalah kunci kesuksesan; jika kita berserah diri kepada Allah, maka segala sesuatu akan menjadi mungkin.",
  "Berikanlah tanpa mengharapkan balasan, dan Allah akan memberikan lebih dari yang kita bayangkan.",
  "Ketika kamu merasa kecewa, ingatlah bahwa Allah memiliki rencana yang lebih baik untukmu.",
  "Keikhlasan adalah kunci kebahagiaan yang abadi.",
  "Jangan terlalu fokus pada apa yang hilang, tetapi syukurilah untuk apa yang masih ada.",
  "Kesabaran adalah kunci kesuksesan; bersabarlah karena setiap kesulitan pasti akan ada jalan keluarnya.",
  "Ketidakpastian hidup adalah ujian iman; percayalah bahwa Allah selalu mengarahkan kita ke yang terbaik.",
  "Bersiaplah untuk berubah, karena perubahan itu adalah bagian dari pertumbuhan.",
  "Latihan bukan hanya untuk tubuh, tapi juga untuk jiwa; setiap rep adalah langkah menuju versi terbaik dirimu.",
  "Setiap keringat adalah investasi dalam kesehatan dan kebahagiaanmu.",
  "Raih kebugaran bukan karena kamu membenci tubuhmu, tapi karena kamu mencintainya dan ingin memberikan yang terbaik baginya.",
  "Jangan hitung rep, buat setiap rep terhitung.",
  "Keberhasilan dalam olahraga bukan hanya tentang fisik, tetapi juga tentang kekuatan mental dan tekad.",
  "Latihan bukanlah beban, tapi hadiah bagi tubuh dan pikiranmu.",
  "Rahasia kebugaran bukan di gym, tapi di konsistensi dan komitmen.",
  "Lakukan untuk hari ini, berikan yang terbaik untuk hari ini, dan esok akan menjadi lebih baik.",
  "Setiap hari adalah kesempatan baru untuk menjadi lebih baik dari hari sebelumnya.",
  "Sesekali kita perlu melepaskan beban pikiran, dan latihan adalah cara terbaik untuk melakukannya.",
  "Jangan hanya bermimpi memiliki tubuh yang sehat, tetapi berkomitmenlah untuk bekerja keras demi mewujudkannya.",
  "Latihan bukan hanya tentang bagaimana tubuhmu terlihat, tetapi juga tentang bagaimana tubuhmu merasa.",
  "Ketika tubuhmu berteriak berhenti, ingatlah bahwa itulah saatnya untuk memberikan yang terbaik.",
  "Ketekunanmu dalam olahraga adalah investasi dalam kesehatan dan kebahagiaanmu di masa depan.",
  "Jangan hanya menjadi penonton dalam hidupmu; ambil peran utama dan bentuk kehidupan sesuai keinginanmu.",
  "Ketika keringatmu menetes, itu adalah bukti bahwa tubuhmu bekerja keras untuk mencapai tujuanmu.",
  "Latihan adalah bentuk cinta kepada dirimu sendiri.",
  "Ketika kamu merasa lelah, ingatlah mengapa kamu memulai perjalanan ini.",
  "Kebugaran adalah perjalanan seumur hidup; nikmati setiap langkahnya.",
  "Jangan hanya berharap untuk meraih hasil, tetapi bersyukurlah untuk setiap usaha yang kamu lakukan.",
  "Latihan bukan hanya tentang kekuatan fisik, tetapi juga tentang kekuatan mental dan tekad yang tidak pernah padam.",
  "Hidup sehat adalah investasi terbaik yang bisa kamu berikan kepada dirimu sendiri.",
  "Tubuh sehat, pikiran sehat, dan jiwa yang damai adalah kunci kebahagiaan sejati.",
  "Setiap kali kamu melewati batas fisikmu, kamu menjadi lebih kuat tidak hanya secara fisik, tetapi juga mental.",
  "Jangan hanya melihat tujuanmu, tetapi nikmatilah setiap langkah dalam perjalananmu.",
  "Latihan adalah cara untuk merayakan kekuatan tubuhmu.",
  "Bekerja keraslah, beristirahatlah dengan baik, dan bangunlah lebih kuat.",
  "Jangan biarkan rintangan menjadi penghalang; jadikan mereka batu loncatan menuju keberhasilanmu.",
  "Ketika kamu merasa malas, ingatlah tujuanmu dan berikan yang terbaik.",
  "Latihan adalah bentuk kedisiplinan diri yang membawa kita ke arah perubahan positif.",
  "Setiap kali kamu berlatih, kamu sedang menghargai hadiah terbesar yang diberikan kepada dirimu sendiri: kesehatan.",
  "Jadilah pahlawan dalam cerita hidupmu sendiri; mulailah dengan menjaga kesehatanmu.",
  "Latihan bukan hanya tentang fisik, tetapi juga tentang karakter dan keteguhan hati.",
  "Jangan fokus pada seberapa jauh kamu harus pergi; fokuslah pada langkah pertamamu hari ini.",
  "Latihan adalah bentuk self-love yang paling murni; kamu memberikan yang terbaik untuk dirimu sendiri.",
  "Setiap gerakanmu adalah pernyataan bahwa kamu menghargai dirimu sendiri dan masa depanmu.",
  "Latihan bukanlah beban, tetapi kehormatan untuk merawat tempat tinggalmu: tubuhmu.",
  "Ketika kamu merasa lelah, ingatlah bahwa lelah adalah tanda bahwa kamu sedang berjuang untuk menjadi lebih baik.",
  "Jangan mencari kesempurnaan, carilah kemajuan. Setiap latihan membawamu lebih dekat ke versi terbaikmu.",
  "Latihan adalah tempat di mana alasan berhenti berhenti dan tekad untuk terus maju dimulai.",
  "Bekerja keraslah untuk dirimu sendiri, bukan untuk mengejar standar kecantikan orang lain.",
  "Setiap peluhmu adalah kemenangan kecil atas dirimu yang lama.",
  "Latihan adalah investasi terbaik yang bisa kamu lakukan untuk masa depanmu.",
  "Jangan lihat latihan sebagai kewajiban, lihatlah sebagai peluang untuk menjadi lebih baik.",
  "Ketika kamu merasa frustasi, ingatlah bahwa setiap latihan membawa kamu lebih dekat ke tujuanmu.",
  "Latihan bukan hanya tentang membangun otot, tetapi juga tentang membangun ketangguhan mental dan spiritual.",
  "Jangan takut mencoba hal baru di dunia fitness; setiap langkah adalah langkah menuju keberhasilan.",
  "Ketika kamu berlatih, kamu tidak hanya membentuk tubuhmu, tetapi juga membentuk karaktermu.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan yang membawa kita menjauh dari versi lama kita dan mendekatkan kita ke versi terbaik kita.",
  "Jangan hanya berbicara tentang perubahan; lakukan sesuatu untuk menciptakan perubahan.",
  "Latihan adalah waktu di mana kamu berinvestasi dalam dirimu sendiri dan masa depanmu.",
  "Jangan takut untuk berhenti sejenak dan merayakan kemajuanmu; setiap usaha layak untuk dihargai.",
  "Latihan adalah pernyataan bahwa kamu memiliki kekuatan untuk mengubah hidupmu sendiri.",
  "Jangan biarkan dirimu menjadi rintangan terbesarmu; lakukan latihan sebagai bentuk pembebasan.",
  "Berlatih dengan konsisten adalah kunci menuju hasil yang konsisten.",
  "Setiap kali kamu berlatih, kamu memberikan dirimu kesempatan untuk menjadi versi terbaik dari dirimu sendiri.",
  "Jangan hanya impikan tubuh yang sehat, tetapi teruslah bergerak menuju ke arah itu.",
  "Latihan bukan hanya tentang mengubah tubuhmu, tetapi juga tentang mengubah pola pikirmu dan gaya hidupmu.",
  "Bekerja keraslah dan tetap rendah hati; kesuksesan dalam olahraga datang kepada mereka yang bersungguh-sungguh.",
  "Latihan bukanlah hukuman, tetapi hadiah bagi tubuh dan pikiranmu.",
  "Jadikan setiap latihan sebagai kesempatan untuk mengenal dirimu sendiri dan melampaui batasanmu.",
  "Bukan tentang seberapa banyak kamu melakukannya, tetapi tentang kualitas dan konsistensi latihanmu.",
  "Latihan adalah bentuk self-care yang paling mendasar dan efektif.",
  "Jangan pernah meremehkan kekuatan latihan; setiap gerakan membentuk tubuhmu dan karaktermu.",
  "Setiap detik yang kamu luangkan untuk berlatih adalah investasi dalam kesehatan jangka panjangmu.",
  "Ketika kamu merasa sulit, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke keberhasilan.",
  "Latihan bukan hanya tentang kebugaran fisik, tetapi juga tentang kebugaran mental dan emosional.",
  "Jadikan setiap latihan sebagai perayaan akan kekuatan dan potensi yang ada dalam dirimu.",
  "Jangan hanya bermimpi tentang hasil; teruslah bekerja keras untuk mencapainya.",
  "Latihan adalah perjalanan yang membawa kita ke arah kebahagiaan dan kesehatan yang sejati.",
  "Ketika kamu merasa lelah, ingatlah bahwa kemajuan terjadi di luar zona nyaman.",
  "Latihan adalah investasi yang memberikan dividen sepanjang hidup.",
  "Setiap gerakan adalah pernyataan bahwa kamu merawat tubuhmu dan menghargai tempat tinggalmu.",
  "Jangan pernah meremehkan kekuatan konsistensi; setiap latihan adalah langkah menuju perubahan positif.",
  "Latihan bukan hanya tentang melibatkan otot, tetapi juga melibatkan hati dan jiwa.",
  "Jadikan setiap hari sebagai kesempatan untuk menciptakan versi terbaik dari dirimu.",
  "Bukan tentang seberapa keras kamu bekerja, tetapi seberapa keras kamu bekerja untuk mencapai tujuanmu.",
  "Latihan adalah cara untuk menciptakan kehidupan yang sehat, bahagia, dan penuh makna.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap latihan membawa kamu lebih dekat ke perubahan yang kamu butuhkan.",
  "Latihan bukan hanya tentang mendapatkan tubuh yang kamu inginkan, tetapi juga tentang menjadi orang yang kamu kagumi.",
  "Jangan hanya berharap untuk meraih hasil, tetapi bersyukurlah untuk setiap langkah perjalananmu.",
  "Latihan adalah kebiasaan yang membentuk karakter; jadilah orang yang berkomitmen untuk berkembang.",
  "Setiap kali kamu melewati batas dirimu, kamu menunjukkan bahwa kamu lebih kuat daripada yang kamu kira.",
  "Jangan lihat latihan sebagai beban, tetapi sebagai investasi dalam kualitas hidupmu.",
  "Latihan bukan hanya tentang mengubah tubuh, tetapi juga tentang menciptakan kebiasaan hidup sehat.",
  "Jadikan setiap gerakan sebagai ekspresi cinta kepada dirimu sendiri dan kehidupan yang kamu ciptakan.",
  "Bukan tentang seberapa sering kamu jatuh, tetapi seberapa sering kamu bangkit kembali; itulah yang membuatmu kuat.",
  "Latihan adalah wujud syukur atas hadiah terbesar yang kamu miliki: tubuh dan kehidupan.",
  "Jangan hanya bermimpi tentang perubahan, tetapi menjadi agen perubahan dengan tindakanmu.",
  "Latihan adalah ritual kecil yang membawa kita ke arah kesuksesan besar.",
  "Setiap gerakanmu adalah pesan kepada dunia bahwa kamu memiliki kekuatan untuk menciptakan perubahan.",
  "Jadikan setiap hari sebagai kesempatan untuk menggali potensi terbaik dalam dirimu.",
  "Bukan tentang seberapa besar kamu bermimpi, tetapi seberapa besar langkah yang kamu ambil untuk mewujudkannya.",
  "Latihan bukan hanya tentang keberanian fisik, tetapi juga tentang keberanian untuk tumbuh dan berubah.",
  "Ketika kamu merasa lelah, ingatlah bahwa tubuhmu memiliki cadangan kekuatan yang lebih besar dari yang kamu pikirkan.",
  "Latihan adalah bentuk kebebasan; setiap gerakan adalah pernyataan bahwa kamu memiliki kendali atas hidupmu.",
  "Jangan hanya meraih bintang, tetapi menjadi bintang yang bersinar dalam kisah hidupmu.",
  "Latihan bukan hanya tentang membangun otot, tetapi juga tentang membangun karakter dan ketekunan.",
  "Jadikan setiap keringat sebagai penanda perjalananmu menuju keberhasilan.",
  "Bukan tentang seberapa berat kamu bekerja, tetapi seberapa keras kamu bekerja untuk mewujudkan impianmu.",
  "Latihan adalah bentuk rasa syukur; kamu memberikan yang terbaik untuk hadiah terbesar yang dimiliki: hidup.",
  "Setiap hari adalah lembaran baru dalam buku perjalananmu; isilah dengan langkah-langkah positif.",
  "Jangan hanya melihat tujuanmu, tetapi nikmatilah setiap langkah dalam perjalananmu.",
  "Latihan adalah kunci untuk membuka potensi tersembunyi dalam dirimu.",
  "Bukan tentang seberapa jauh kamu harus pergi, tetapi seberapa jauh kamu telah datang.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Latihan bukan hanya tentang berat badan yang bisa kamu angkat, tetapi juga tentang beban yang bisa kamu lepaskan.",
  "Jangan takut untuk mencoba tantangan baru; setiap kesulitan adalah kesempatan untuk tumbuh.",
  "Latihan bukan hanya tentang bagaimana kamu melihat, tetapi juga tentang bagaimana kamu merasa tentang dirimu sendiri.",
  "Ketika kamu merasa putus asa, ingatlah bahwa setiap langkah membawa kamu lebih dekat ke perubahan yang kamu inginkan.",
  "Jadilah sumber inspirasi bagi dirimu sendiri; buat setiap latihan menjadi pencapaian kecil yang membanggakan.",
  "Latihan adalah perjalanan tanpa akhir menuju versi terbaik dari dirimu sendiri.",
  "Berlatih adalah pernyataan bahwa kamu menghargai dan mencintai dirimu sendiri.",
  "Jangan terlalu fokus pada skala, tetapi fokus pada bagaimana tubuh dan pikiranmu merasa setelah setiap latihan.",
  "Keberhasilan adalah hasil dari kesabaran.",
  "Berikanlah yang terbaik, dan biarkan Allah yang menjalankan yang terakhir.",
  "Doa adalah senjata seorang mukmin.",
  "Tidak ada batasan untuk kebaikan yang dapat kita lakukan.",
  "Allah tidak membebani seseorang melampaui batas kemampuannya.",
  "Sabar adalah kuncinya, hasilnya adalah indah.",
  "Ketika kamu merasa lelah berdoalah, bukan menyerah.",
  "Teruslah berusaha, karena setiap usaha memiliki hasil.",
  "Rencana Allah selalu lebih baik dari impian kita.",
  "Setiap ujian adalah pembelajaran yang berharga.",
  "Takdir yang buruk adalah takdir yang kita keluhkan, tapi mungkin itu yang terbaik bagi kita.",
  "Saat kamu merasa sendirian, ingatlah bahwa Allah selalu bersamamu.",
  "Jangan pernah takut untuk memulai sesuatu, karena Allah bersama mereka yang berani.",
  "Kesulitan adalah ujian, dan kesabaran adalah kuncinya.",
  "Jangan pernah berhenti berdoa, karena Allah selalu mendengarkan.",
  "Allah lebih tahu apa yang baik untuk kita, bahkan ketika kita tidak tahu.",
  "Setiap langkah kebaikan yang kita lakukan adalah investasi untuk akhirat.",
  "Hidup ini sementara, persiapkan dirimu untuk kehidupan yang abadi.",
  "Allah lebih dekat pada kita daripada urat leher kita.",
  "Ketika pintu dunia tertutup, pintu surga selalu terbuka.",
  "Jangan pernah merasa sendirian, karena Allah selalu bersamamu.",
  "Sesungguhnya bersama kesulitan ada kemudahan.",
  "Ketika kita bersyukur, Allah memberikan lebih banyak alasan untuk bersyukur.",
  "Jangan pernah menyerah, karena setiap kesulitan pasti ada jalan keluarnya.",
  "Doa yang tulus adalah kunci terkuat yang membuka pintu terberat.",
  "Keikhlasan adalah kunci kesuksesan yang sejati.",
  "Bersabarlah dalam ujian, karena setiap kesulitan pasti ada kemudahan.",
  "Jangan pernah merasa rendah diri, karena kamu adalah ciptaan Allah yang luar biasa.",
  "Allah tidak pernah tidur, Dia selalu menjaga dan melindungi kita.",
  "Bentuk ketabahanmu dalam doa, bukan dalam keluh kesah.",
  "Sesungguhnya Allah bersama orang-orang yang sabar.",
  "Allah tahu apa yang terbaik untuk kita, meski terkadang kita tidak mengerti.",
  "Doa adalah kunci yang menghubungkan kita dengan Allah.",
  "Setiap ujian adalah pembuktian seberapa besar kepercayaan kita pada Allah.",
  "Allah memberikan ujian kepada hamba-Nya yang dicintai.",
  "Kepercayaan kepada Allah adalah kekuatan yang tak tergoyahkan.",
  "Hidup ini hanya sementara, persiapkan dirimu untuk kehidupan yang abadi.",
  "Jangan pernah ragu pada rencana Allah, karena rencana-Nya selalu lebih baik dari yang kita bayangkan.",
  "Saat kita lemah, itulah saat Allah memberikan kekuatan kepada kita.",
  "Sesungguhnya setiap detik kehidupan adalah kesempatan untuk bertaubat.",
  "Allah adalah pelindung terbaik, tempat kita berlindung saat ada masalah.",
  "Ketika kita tidak bisa melihat jalan, itulah saat Allah membuka pintu.",
  "Doa adalah senjata yang dapat mengubah takdir.",
  "Saat kita terjatuh, itulah saat kita dapat memohon pertolongan kepada Allah.",
  "Allah selalu memberikan yang terbaik pada waktunya yang terbaik.",
  "Ketika pintu dunia tertutup, itulah saat Allah membuka pintu surga.",
  "Jangan pernah ragu pada rahmat Allah, karena rahmat-Nya meliputi segala sesuatu.",
  "Setiap ujian adalah peluang untuk mendekatkan diri kepada Allah.",
  "Bersyukurlah dalam kesulitan, karena itu adalah jalan menuju kebahagiaan.",
  "Hidup ini adalah perjalanan menuju Allah, jangan lelah untuk berusaha.",
  "Ketika kita menyerahkan segalanya kepada Allah, itulah saat Dia memberikan yang terbaik untuk kita.",
  "Allah tidak memberikan ujian kepada hambanya dibatas kemampuannya",
  "Jika kamu merasa hidupmu malang coba ke Bekasi aja",
  "Cukup Antartika yang jauh Antarkita jangan",
  "Bermimpilah setinggi langit Sampe kamu nabrak satelit",
];

function getRandomQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  const randomQuote = quotes[randomIndex];
  return { quote: randomQuote, index: randomIndex + 1 }; // Tambah 1 karena indeks dimulai dari 1
}

function displayRandomQuote() {
  const quoteContainer = document.getElementById("quote");
  const indexContainer = document.getElementById("index");

  const { quote, index } = getRandomQuote();

  quoteContainer.textContent = `${index}. ${quote}`;
  indexContainer.textContent = `Index: ${index}`;
}

const refreshButton = document.getElementById("refresh-button");
refreshButton.addEventListener("click", displayRandomQuote);

// Tampilkan kutipan pertama saat halaman dimuat
displayRandomQuote();

